import { lingui } from "@lingui/vite-plugin";
import tailwindcss from "@tailwindcss/vite";
import { tanstackStart } from "@tanstack/react-start/plugin/vite";
import { defineConfig } from "vite";
import tsConfigPaths from "vite-tsconfig-paths";

export default defineConfig({
	server: {
		port: 3000,
	},
	build: {
		target: "esnext",
	},
	plugins: [
		lingui(),
		tailwindcss(),
		tsConfigPaths({
			projects: ["./tsconfig.json"],
		}),
		tanstackStart({
			tsr: {
				routeTreeFileHeader: [
					"/** biome-ignore-all lint/suspicious/noExplicitAny: code generated by @tanstack/react-start */",
				],
				quoteStyle: "double",
			},
			react: {
				babel: {
					plugins: ["@lingui/babel-plugin-lingui-macro"],
				},
			},
		}),
	],
});
